### ISSUE TITLE
Generate proper model for nullable fields

### ISSUE THREAD

**Issue by taaraora** [taaraora/gnostic-go-generator#1]
If property marked with `nullable: true` filed it should be generated as a pointer type.
  ```yaml
account:
      type: object
      properties:
        id:
          type: string
          description: account unique identifier
        createdAt:
          type: string
          description: account creation timestamp
          format: date-time
          readOnly: true
        updatedAt:
          nullable: true
          type: string
          description: account update timestamp
          format: date-time
          readOnly: true
        suspended:
          type: boolean
          description: if true users from this account can't login and spin up clusters
        dpaStatus:
          type: string
          description: |
            status of data processing agreement document which should be signed between two data processing actors under GDPR
            - requestAction - the user hasen't interacted with the banner
            - pending - they are waiting on up to sign the DPA
            - exempt - the user selected that they are exempt from the DPA requirement
            - received - we have a DPA from this account signed by us and them
          enum:
            - requestAction
            - pending
            - exempt
            - received
        dpaUpdatedAt:
          nullable: true
          type: string
          description: last update timestamp of dpaStatus field
          format: date-time
          readOnly: true
        company:
          maxLength: 255
          type: string
          description: Company the account belongs to
        email:
          type: string
          description: The company wide email for the account.  Up for debate on if
            we keep this variable
          format: email
  ```

Should generate struct:

```go
type Account struct {
	Id           string `json:"id,omitempty"`
	CreatedAt    string `json:"createdAt,omitempty"`
	UpdatedAt    *string `json:"updatedAt,omitempty"`
	Suspended    bool   `json:"suspended,omitempty"`
	DpaStatus    string `json:"dpaStatus,omitempty"`
	DpaUpdatedAt *string `json:"dpaUpdatedAt,omitempty"`
	Company      string `json:"company,omitempty"`
	Email        string `json:"email,omitempty"`
}
```
