### ISSUE TITLE
Add db tags for generated struct fields

### ISSUE THREAD

**Issue by taaraora** [taaraora/gnostic-go-generator#2]
When filed name consists form more than one word, we should generate snake cased db tag for that field. E. G.
for this entity:
```yaml
    account:
      type: object
      properties:
        id:
          type: string
          description: account unique identifier
        createdAt:
          type: string
          description: account creation timestamp
          format: date-time
          readOnly: true
        updatedAt:
          nullable: true
          type: string
          description: account update timestamp
          format: date-time
          readOnly: true
        suspended:
          type: boolean
          description: if true users from this account can't login
        dpaStatus:
          type: string
        dpaUpdatedAt:
          nullable: true
          type: string
          format: date-time
          readOnly: true
        company:
          maxLength: 255
          type: string
          description: Company the account belongs to
        email:
          type: string
          format: email
```

We should get the next struct:
```golang
type Account struct {
	Id           string `json:"id,omitempty"`
	CreatedAt    string `json:"createdAt,omitempty" db:"created_at"`
	UpdatedAt    *string `json:"updatedAt,omitempty" db:"updated_at"`
	Suspended    bool   `json:"suspended,omitempty"`
	DpaStatus    string `json:"dpaStatus,omitempty" db:"dpa_status"`
	DpaUpdatedAt *string `json:"dpaUpdatedAt,omitempty" db:"dpa_updated_at"`
	Company      string `json:"company,omitempty"`
	Email        string `json:"email,omitempty"`
}
```
